package securityfinalproject;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
            int port = 7999;
            ServerSocket server = new ServerSocket(port);

            try(Socket s = server.accept()) {

                // YOU NEED TO DO THESE STEPS:
                // -Read the key from the file generated by the client.
                // -Use the key to decrypt the incoming message from socket s.		
                // -Print out the decrypt String to see if it matches the orignal message.

                //Read key from file
                ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.xx"));
                Key k = (Key)in.readObject();

                Cipher c;

                c = Cipher.getInstance("DES/ECB/PKCS5Padding");

                c.init(Cipher.DECRYPT_MODE, k);

                DataInputStream dIn = new DataInputStream(s.getInputStream());
                int length = dIn.readInt();

                    if(length>0){
                        byte [] message = new byte[length];
                        dIn.readFully(message, 0, message.length);
                        byte[] decryptedText = c.doFinal(message);
                        System.out.println(new String(decryptedText));
                    }

            }

    }
}